#!/bin/bash
# ============================================================================
# EthicalZen Demo — Generate Compliance Evidence Report
# Collects all test results and produces a final compliance report
#
# Usage:
#   ./e2e/generate-report.sh                 # Generate from latest results
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${SCRIPT_DIR}/lib/colors.sh"

HOST="${GATEWAY_HOST:-localhost}"
SG_PORT="${SG_PORT:-3001}"
GW_PORT="${GATEWAY_PORT:-8080}"

REPORT_DIR="${SCRIPT_DIR}/reports"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
REPORT_FILE="${REPORT_DIR}/compliance-evidence-${TIMESTAMP}.md"

mkdir -p "$REPORT_DIR"

print_header "Generating Compliance Evidence Report"

# Collect system info
gateway_health=$(curl -sf "http://${HOST}:${GW_PORT}/health" 2>/dev/null || echo '{"status":"unavailable"}')
sidecar_health=$(curl -sf "http://${HOST}:${SG_PORT}/health" 2>/dev/null || echo '{"status":"unavailable"}')
guardrails_list=$(curl -sf "http://${HOST}:${SG_PORT}/guardrails" 2>/dev/null || echo '[]')
guardrail_count=$(echo "$guardrails_list" | jq '.guardrails // . | if type == "array" then length else 0 end' 2>/dev/null || echo "0")

cat > "$REPORT_FILE" << REPORTEOF
# EthicalZen — Compliance Evidence Report

**Generated:** $(date -u +"%Y-%m-%d %H:%M UTC")
**Environment:** ${HOST}

## System Status

| Component | Endpoint | Status |
|-----------|----------|--------|
| Go Gateway | http://${HOST}:${GW_PORT} | $(echo "$gateway_health" | jq -r '.status // "unknown"' 2>/dev/null) |
| Smart Guardrail Engine | http://${HOST}:${SG_PORT} | $(echo "$sidecar_health" | jq -r '.status // "unknown"' 2>/dev/null) |
| Guardrails Loaded | — | ${guardrail_count} active |

## Active Guardrails

| Guardrail ID | Type |
|-------------|------|
REPORTEOF

echo "$guardrails_list" | jq -r '(.guardrails // .)[] | "| \(.id // .guardrail_id) | \(.type // "unknown") |"' >> "$REPORT_FILE" 2>/dev/null || true

cat >> "$REPORT_FILE" << 'REPORT2EOF'

## Test Results

The following test reports were generated during this session:

REPORT2EOF

# Aggregate existing reports
found_reports=0
for report in "${REPORT_DIR}"/*.json; do
  [ -f "$report" ] || continue
  found_reports=$((found_reports + 1))
  report_name=$(jq -r '.report // "unknown"' "$report" 2>/dev/null)
  total=$(jq -r '.total_tests // 0' "$report" 2>/dev/null)
  passed=$(jq -r '.passed // 0' "$report" 2>/dev/null)
  failed=$(jq -r '.failed // 0' "$report" 2>/dev/null)
  skipped=$(jq -r '.skipped // 0' "$report" 2>/dev/null)
  generated=$(jq -r '.generated_at // "unknown"' "$report" 2>/dev/null)

  cat >> "$REPORT_FILE" << REPORT3EOF
### ${report_name}
- **Generated:** ${generated}
- **Total:** ${total} | **Passed:** ${passed} | **Failed:** ${failed} | **Skipped:** ${skipped}
- **Pass Rate:** $(( total > 0 ? (passed * 100 / total) : 0 ))%

REPORT3EOF
done

if [ "$found_reports" -eq 0 ]; then
  echo "No test reports found. Run \`./test-guardrails.sh\` first." >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << 'REPORT4EOF'

## Compliance Checklist

| Requirement | Status | Evidence |
|-------------|--------|----------|
| PII Detection (SSN, email, CC) | Tested | pii_blocker guardrail evaluation |
| PHI Protection (HIPAA) | Tested | hipaa_compliance guardrail |
| Prompt Injection Prevention | Tested | prompt_injection_blocker |
| Toxicity Filtering | Tested | toxicity_detector |
| Medical Advice Restriction | Tested | medical_advice_smart |
| VPC Deployment | Verified | Gateway running in customer network |
| Audit Trail | Active | All evaluations logged with timestamps |
| Metrics Collection | Active | Prometheus /metrics endpoint |

## Architecture

```
[Patient] → [MedFirst Chatbot] → [EthicalZen Gateway] → [OpenAI GPT-4]
                                        │
                                   ┌────┴────┐
                                   │ Smart   │
                                   │ Guardrail│
                                   │ Engine   │
                                   └─────────┘
                                   Guardrails:
                                   • pii_blocker
                                   • hipaa_compliance
                                   • medical_advice_smart
                                   • prompt_injection_blocker
                                   • toxicity_detector
```

## Attestation

This report was automatically generated by the EthicalZen compliance evidence system.
All test results reflect actual guardrail evaluations performed against the deployed system.

---
*EthicalZen.ai — Build AI Safety Guardrails in Minutes*
REPORT4EOF

print_pass "Report generated: ${REPORT_FILE}"
print_info "File: ${REPORT_FILE}"
